# Generated by Django 2.1.1 on 2018-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerID', models.TextField()),
                ('asin', models.TextField()),
                ('reviewText', models.TextField()),
                ('overall', models.DecimalField(decimal_places=2, max_digits=3)),
                ('summary', models.TextField()),
                ('unixReviewTime', models.BigIntegerField()),
                ('reviewTime', models.DateField()),
            ],
            options={
                'ordering': ['-reviewTime'],
            },
        ),
    ]
