# Generated by Django 2.1.1 on 2018-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonreview',
            name='reviewText_noStopWords',
            field=models.TextField(default=None, null=True),
        ),
    ]
